Update basecamp3.sh
adds apple silicon option for basecamp3 label.

❯ sudo /Users/danny/Documents/GitHub/Installomator/assemble.sh basecamp3 DEBUG=0

Password:
2024-03-25 11:05:02 : REQ   : basecamp3 : ################## Start Installomator v. 10.6beta, date 2024-03-25
2024-03-25 11:05:02 : INFO  : basecamp3 : ################## Version: 10.6beta
2024-03-25 11:05:02 : INFO  : basecamp3 : ################## Date: 2024-03-25
2024-03-25 11:05:02 : INFO  : basecamp3 : ################## basecamp3
2024-03-25 11:05:02 : DEBUG : basecamp3 : DEBUG mode 1 enabled.
2024-03-25 11:05:03 : INFO  : basecamp3 : setting variable from argument DEBUG=0
2024-03-25 11:05:03 : DEBUG : basecamp3 : name=Basecamp 3
2024-03-25 11:05:03 : DEBUG : basecamp3 : appName=Basecamp 3.app
2024-03-25 11:05:03 : DEBUG : basecamp3 : type=dmg
2024-03-25 11:05:03 : DEBUG : basecamp3 : archiveName=
2024-03-25 11:05:03 : DEBUG : basecamp3 : downloadURL=https://bc3-desktop.s3.amazonaws.com/mac_arm64/basecamp3_arm64.dmg
2024-03-25 11:05:03 : DEBUG : basecamp3 : curlOptions=
2024-03-25 11:05:03 : DEBUG : basecamp3 : appNewVersion=
2024-03-25 11:05:03 : DEBUG : basecamp3 : appCustomVersion function: Not defined
2024-03-25 11:05:03 : DEBUG : basecamp3 : versionKey=CFBundleShortVersionString
2024-03-25 11:05:03 : DEBUG : basecamp3 : packageID=
2024-03-25 11:05:03 : DEBUG : basecamp3 : pkgName=
2024-03-25 11:05:03 : DEBUG : basecamp3 : choiceChangesXML=
2024-03-25 11:05:03 : DEBUG : basecamp3 : expectedTeamID=2WNYUYRS7G
2024-03-25 11:05:03 : DEBUG : basecamp3 : blockingProcesses=
2024-03-25 11:05:03 : DEBUG : basecamp3 : installerTool=
2024-03-25 11:05:03 : DEBUG : basecamp3 : CLIInstaller=
2024-03-25 11:05:03 : DEBUG : basecamp3 : CLIArguments=
2024-03-25 11:05:03 : DEBUG : basecamp3 : updateTool=
2024-03-25 11:05:03 : DEBUG : basecamp3 : updateToolArguments=
2024-03-25 11:05:03 : DEBUG : basecamp3 : updateToolRunAsCurrentUser=
2024-03-25 11:05:03 : INFO  : basecamp3 : BLOCKING_PROCESS_ACTION=tell_user
2024-03-25 11:05:03 : INFO  : basecamp3 : NOTIFY=success
2024-03-25 11:05:03 : INFO  : basecamp3 : LOGGING=DEBUG
2024-03-25 11:05:03 : INFO  : basecamp3 : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-03-25 11:05:03 : INFO  : basecamp3 : Label type: dmg
2024-03-25 11:05:03 : INFO  : basecamp3 : archiveName: Basecamp 3.dmg
2024-03-25 11:05:03 : INFO  : basecamp3 : no blocking processes defined, using Basecamp 3 as default
2024-03-25 11:05:03 : DEBUG : basecamp3 : Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.8H7wbp5nOB
2024-03-25 11:05:03 : INFO  : basecamp3 : App(s) found: /Applications/Basecamp 3.app
2024-03-25 11:05:03 : INFO  : basecamp3 : found app at /Applications/Basecamp 3.app, version 2.3.14, on versionKey CFBundleShortVersionString
2024-03-25 11:05:03 : INFO  : basecamp3 : appversion: 2.3.14
2024-03-25 11:05:03 : INFO  : basecamp3 : Latest version not specified.
2024-03-25 11:05:03 : REQ   : basecamp3 : Downloading https://bc3-desktop.s3.amazonaws.com/mac_arm64/basecamp3_arm64.dmg to Basecamp 3.dmg
2024-03-25 11:05:03 : DEBUG : basecamp3 : No Dialog connection, just download
2024-03-25 11:05:15 : DEBUG : basecamp3 : File list: -rw-r--r--@ 1 root  wheel    87M Mar 25 11:05 Basecamp 3.dmg
2024-03-25 11:05:15 : DEBUG : basecamp3 : File type: Basecamp 3.dmg: zlib compressed data
2024-03-25 11:05:15 : DEBUG : basecamp3 : curl output was:
*   Trying 3.5.25.212:443...
* Connected to bc3-desktop.s3.amazonaws.com (3.5.25.212) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [333 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4969 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.s3.amazonaws.com
*  start date: Oct 10 00:00:00 2023 GMT
*  expire date: Jul  3 23:59:59 2024 GMT
*  subjectAltName: host "bc3-desktop.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/1.1
> GET /mac_arm64/basecamp3_arm64.dmg HTTP/1.1
> Host: bc3-desktop.s3.amazonaws.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: 9u7JWHepkIR6cva4fiYeGZjtAwNuMeMN4PAuK/8Hh8lIDXY5Ru0N6wZkKgzol4WrlApH4e9nyyFQd0jewxUtsqpvaQuqJ2ZG74+Ug68MVb4=
< x-amz-request-id: 2VYE1JH7KMRBB8H9
< Date: Mon, 25 Mar 2024 16:05:04 GMT
< Last-Modified: Fri, 22 Sep 2023 13:04:24 GMT
< ETag: "08ff7fc079f73017775ac746fa196b34"
< x-amz-server-side-encryption: AES256
< x-amz-version-id: 0kJiLS4xpTxpZsuGnbRfN3_qxccsMFaK
< Accept-Ranges: bytes
< Content-Type: application/x-apple-diskimage
< Server: AmazonS3
< Content-Length: 91727114
<
{ [1435 bytes data]
* Connection #0 to host bc3-desktop.s3.amazonaws.com left intact

2024-03-25 11:05:15 : REQ   : basecamp3 : no more blocking processes, continue with update
2024-03-25 11:05:15 : REQ   : basecamp3 : Installing Basecamp 3
2024-03-25 11:05:15 : INFO  : basecamp3 : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.8H7wbp5nOB/Basecamp 3.dmg
2024-03-25 11:05:19 : DEBUG : basecamp3 : Debugging enabled, dmgmount output was:
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $C34A8150
Checksumming GPT Header (Primary GPT Header : 1)…
GPT Header (Primary GPT Header : 1): verified   CRC32 $C9462BE1
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $FE424713
Checksumming  (Apple_Free : 3)…
(Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
disk image (Apple_HFS : 4): verified   CRC32 $E395E400
Checksumming  (Apple_Free : 5)…
(Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $FE424713
Checksumming GPT Header (Backup GPT Header : 7)…
GPT Header (Backup GPT Header : 7): verified   CRC32 $0DE1FF3B
verified   CRC32 $B161226F
/dev/disk4          	GUID_partition_scheme
/dev/disk4s1        	Apple_HFS                      	/Volumes/Basecamp 3

2024-03-25 11:05:19 : INFO  : basecamp3 : Mounted: /Volumes/Basecamp 3
2024-03-25 11:05:19 : INFO  : basecamp3 : Verifying: /Volumes/Basecamp 3/Basecamp 3.app
2024-03-25 11:05:19 : DEBUG : basecamp3 : App size: 214M	/Volumes/Basecamp 3/Basecamp 3.app
2024-03-25 11:05:20 : DEBUG : basecamp3 : Debugging enabled, App Verification output was:
/Volumes/Basecamp 3/Basecamp 3.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Basecamp, LLC (2WNYUYRS7G)

2024-03-25 11:05:20 : INFO  : basecamp3 : Team ID matching: 2WNYUYRS7G (expected: 2WNYUYRS7G )
2024-03-25 11:05:20 : INFO  : basecamp3 : Downloaded version of Basecamp 3 is 2.3.14 on versionKey CFBundleShortVersionString, same as installed.
2024-03-25 11:05:20 : DEBUG : basecamp3 : Unmounting /Volumes/Basecamp 3
2024-03-25 11:05:20 : DEBUG : basecamp3 : Debugging enabled, Unmounting output was:
"disk4" ejected.
2024-03-25 11:05:20 : DEBUG : basecamp3 : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.8H7wbp5nOB
2024-03-25 11:05:20 : DEBUG : basecamp3 : Debugging enabled, Deleting tmpDir output was:
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.8H7wbp5nOB/Basecamp 3.dmg
2024-03-25 11:05:20 : DEBUG : basecamp3 : /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.8H7wbp5nOB
2024-03-25 11:05:20 : INFO  : basecamp3 : Installomator did not close any apps, so no need to reopen any apps.
2024-03-25 11:05:20 : REG   : basecamp3 : No new version to install
2024-03-25 11:05:20 : REQ   : basecamp3 : ################## End Installomator, exit code 0

❯ sudo /Users/danny/Documents/GitHub/Installomator/assemble.sh basecamp3 DEBUG=0

2024-03-25 11:05:25 : REQ   : basecamp3 : ################## Start Installomator v. 10.6beta, date 2024-03-25
2024-03-25 11:05:25 : INFO  : basecamp3 : ################## Version: 10.6beta
2024-03-25 11:05:25 : INFO  : basecamp3 : ################## Date: 2024-03-25
2024-03-25 11:05:25 : INFO  : basecamp3 : ################## basecamp3
2024-03-25 11:05:25 : DEBUG : basecamp3 : DEBUG mode 1 enabled.
2024-03-25 11:05:25 : INFO  : basecamp3 : setting variable from argument DEBUG=0
2024-03-25 11:05:25 : DEBUG : basecamp3 : name=Basecamp 3
2024-03-25 11:05:25 : DEBUG : basecamp3 : appName=Basecamp 3.app
2024-03-25 11:05:25 : DEBUG : basecamp3 : type=dmg
2024-03-25 11:05:25 : DEBUG : basecamp3 : archiveName=
2024-03-25 11:05:25 : DEBUG : basecamp3 : downloadURL=https://bc3-desktop.s3.amazonaws.com/mac_arm64/basecamp3_arm64.dmg
2024-03-25 11:05:25 : DEBUG : basecamp3 : curlOptions=
2024-03-25 11:05:25 : DEBUG : basecamp3 : appNewVersion=
2024-03-25 11:05:25 : DEBUG : basecamp3 : appCustomVersion function: Not defined
2024-03-25 11:05:25 : DEBUG : basecamp3 : versionKey=CFBundleShortVersionString
2024-03-25 11:05:25 : DEBUG : basecamp3 : packageID=
2024-03-25 11:05:25 : DEBUG : basecamp3 : pkgName=
2024-03-25 11:05:25 : DEBUG : basecamp3 : choiceChangesXML=
2024-03-25 11:05:25 : DEBUG : basecamp3 : expectedTeamID=2WNYUYRS7G
2024-03-25 11:05:25 : DEBUG : basecamp3 : blockingProcesses=
2024-03-25 11:05:25 : DEBUG : basecamp3 : installerTool=
2024-03-25 11:05:25 : DEBUG : basecamp3 : CLIInstaller=
2024-03-25 11:05:25 : DEBUG : basecamp3 : CLIArguments=
2024-03-25 11:05:25 : DEBUG : basecamp3 : updateTool=
2024-03-25 11:05:25 : DEBUG : basecamp3 : updateToolArguments=
2024-03-25 11:05:25 : DEBUG : basecamp3 : updateToolRunAsCurrentUser=
2024-03-25 11:05:25 : INFO  : basecamp3 : BLOCKING_PROCESS_ACTION=tell_user
2024-03-25 11:05:25 : INFO  : basecamp3 : NOTIFY=success
2024-03-25 11:05:25 : INFO  : basecamp3 : LOGGING=DEBUG
2024-03-25 11:05:25 : INFO  : basecamp3 : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-03-25 11:05:25 : INFO  : basecamp3 : Label type: dmg
2024-03-25 11:05:25 : INFO  : basecamp3 : archiveName: Basecamp 3.dmg
2024-03-25 11:05:25 : INFO  : basecamp3 : no blocking processes defined, using Basecamp 3 as default
2024-03-25 11:05:25 : DEBUG : basecamp3 : Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.UeJfvcDX3I
2024-03-25 11:05:25 : INFO  : basecamp3 : name: Basecamp 3, appName: Basecamp 3.app
2024-03-25 11:05:25.737 mdfind[78188:754584] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2024-03-25 11:05:25.737 mdfind[78188:754584] [UserQueryParser] Loading keywords and predicates for locale "en"
2024-03-25 11:05:25.788 mdfind[78188:754584] Couldn't determine the mapping between prefab keywords and predicates.
2024-03-25 11:05:25 : WARN  : basecamp3 : No previous app found
2024-03-25 11:05:25 : WARN  : basecamp3 : could not find Basecamp 3.app
2024-03-25 11:05:25 : INFO  : basecamp3 : appversion:
2024-03-25 11:05:25 : INFO  : basecamp3 : Latest version not specified.
2024-03-25 11:05:25 : REQ   : basecamp3 : Downloading https://bc3-desktop.s3.amazonaws.com/mac_arm64/basecamp3_arm64.dmg to Basecamp 3.dmg
2024-03-25 11:05:25 : DEBUG : basecamp3 : No Dialog connection, just download
2024-03-25 11:05:36 : DEBUG : basecamp3 : File list: -rw-r--r--@ 1 root  wheel    87M Mar 25 11:05 Basecamp 3.dmg
2024-03-25 11:05:36 : DEBUG : basecamp3 : File type: Basecamp 3.dmg: zlib compressed data
2024-03-25 11:05:36 : DEBUG : basecamp3 : curl output was:
*   Trying 52.217.132.225:443...
* Connected to bc3-desktop.s3.amazonaws.com (52.217.132.225) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [333 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4969 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.s3.amazonaws.com
*  start date: Oct 10 00:00:00 2023 GMT
*  expire date: Jul  3 23:59:59 2024 GMT
*  subjectAltName: host "bc3-desktop.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/1.1
> GET /mac_arm64/basecamp3_arm64.dmg HTTP/1.1
> Host: bc3-desktop.s3.amazonaws.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: G0WC2ipALzztPSImXcF/EfHK15PhWpfDOIXJAVyTXvHmVXthGBWrr7PrinIM209B6ZV4tG4cB/o=
< x-amz-request-id: 6SJC7QD36APERP7T
< Date: Mon, 25 Mar 2024 16:05:27 GMT
< Last-Modified: Fri, 22 Sep 2023 13:04:24 GMT
< ETag: "08ff7fc079f73017775ac746fa196b34"
< x-amz-server-side-encryption: AES256
< x-amz-version-id: 0kJiLS4xpTxpZsuGnbRfN3_qxccsMFaK
< Accept-Ranges: bytes
< Content-Type: application/x-apple-diskimage
< Server: AmazonS3
< Content-Length: 91727114
<
{ [16384 bytes data]
* Connection #0 to host bc3-desktop.s3.amazonaws.com left intact

2024-03-25 11:05:36 : REQ   : basecamp3 : no more blocking processes, continue with update
2024-03-25 11:05:36 : REQ   : basecamp3 : Installing Basecamp 3
2024-03-25 11:05:36 : INFO  : basecamp3 : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.UeJfvcDX3I/Basecamp 3.dmg
2024-03-25 11:05:39 : DEBUG : basecamp3 : Debugging enabled, dmgmount output was:
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $C34A8150
Checksumming GPT Header (Primary GPT Header : 1)…
GPT Header (Primary GPT Header : 1): verified   CRC32 $C9462BE1
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $FE424713
Checksumming  (Apple_Free : 3)…
(Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
disk image (Apple_HFS : 4): verified   CRC32 $E395E400
Checksumming  (Apple_Free : 5)…
(Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $FE424713
Checksumming GPT Header (Backup GPT Header : 7)…
GPT Header (Backup GPT Header : 7): verified   CRC32 $0DE1FF3B
verified   CRC32 $B161226F
/dev/disk4          	GUID_partition_scheme
/dev/disk4s1        	Apple_HFS                      	/Volumes/Basecamp 3

2024-03-25 11:05:39 : INFO  : basecamp3 : Mounted: /Volumes/Basecamp 3
2024-03-25 11:05:39 : INFO  : basecamp3 : Verifying: /Volumes/Basecamp 3/Basecamp 3.app
2024-03-25 11:05:39 : DEBUG : basecamp3 : App size: 214M	/Volumes/Basecamp 3/Basecamp 3.app
2024-03-25 11:05:40 : DEBUG : basecamp3 : Debugging enabled, App Verification output was:
/Volumes/Basecamp 3/Basecamp 3.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Basecamp, LLC (2WNYUYRS7G)

2024-03-25 11:05:40 : INFO  : basecamp3 : Team ID matching: 2WNYUYRS7G (expected: 2WNYUYRS7G )
2024-03-25 11:05:40 : INFO  : basecamp3 : Installing Basecamp 3 version 2.3.14 on versionKey CFBundleShortVersionString.
2024-03-25 11:05:40 : INFO  : basecamp3 : App has LSMinimumSystemVersion: 10.13
2024-03-25 11:05:40 : INFO  : basecamp3 : Copy /Volumes/Basecamp 3/Basecamp 3.app to /Applications
2024-03-25 11:05:41 : DEBUG : basecamp3 : Debugging enabled, App copy output was:
Copying /Volumes/Basecamp 3/Basecamp 3.app

2024-03-25 11:05:41 : WARN  : basecamp3 : Changing owner to danny
2024-03-25 11:05:41 : INFO  : basecamp3 : Finishing...
2024-03-25 11:05:44 : INFO  : basecamp3 : App(s) found: /Applications/Basecamp 3.app
2024-03-25 11:05:44 : INFO  : basecamp3 : found app at /Applications/Basecamp 3.app, version 2.3.14, on versionKey CFBundleShortVersionString
2024-03-25 11:05:44 : REQ   : basecamp3 : Installed Basecamp 3, version 2.3.14
2024-03-25 11:05:44 : INFO  : basecamp3 : notifying
ERROR: Notifications are not allowed for this application
2024-03-25 11:05:44 : DEBUG : basecamp3 : Unmounting /Volumes/Basecamp 3
2024-03-25 11:05:44 : DEBUG : basecamp3 : Debugging enabled, Unmounting output was:
"disk4" ejected.
2024-03-25 11:05:44 : DEBUG : basecamp3 : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.UeJfvcDX3I
2024-03-25 11:05:44 : DEBUG : basecamp3 : Debugging enabled, Deleting tmpDir output was:
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.UeJfvcDX3I/Basecamp 3.dmg
2024-03-25 11:05:44 : DEBUG : basecamp3 : /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.UeJfvcDX3I
2024-03-25 11:05:44 : INFO  : basecamp3 : Installomator did not close any apps, so no need to reopen any apps.
2024-03-25 11:05:44 : REQ   : basecamp3 : All done!
2024-03-25 11:05:44 : REQ   : basecamp3 : ################## End Installomator, exit code 0