Update clickshare.sh
added a user agent to the curl request to work around cloudflare blocking the request.

Output when the appNewVersion works:
```
sudo zsh /usr/local/Installomator/Installomator.sh clickshare
2024-12-17 17:22:42 : REQ   : clickshare : ################## Start Installomator v. 10.6, date 2024-08-30
2024-12-17 17:22:43 : INFO  : clickshare : ################## Version: 10.6
2024-12-17 17:22:43 : INFO  : clickshare : ################## Date: 2024-08-30
2024-12-17 17:22:43 : INFO  : clickshare : ################## clickshare
2024-12-17 17:22:46 : INFO  : clickshare : BLOCKING_PROCESS_ACTION=tell_user
2024-12-17 17:22:46 : INFO  : clickshare : NOTIFY=success
2024-12-17 17:22:46 : INFO  : clickshare : LOGGING=INFO
2024-12-17 17:22:46 : INFO  : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-12-17 17:22:46 : INFO  : clickshare : Label type: appInDmgInZip
2024-12-17 17:22:46 : INFO  : clickshare : archiveName: ClickShare.zip
2024-12-17 17:22:46 : INFO  : clickshare : no blocking processes defined, using ClickShare as default
2024-12-17 17:22:46 : INFO  : clickshare : App(s) found: /Applications/ClickShare.app
2024-12-17 17:22:46 : INFO  : clickshare : found app at /Applications/ClickShare.app, version 4.42.0-b18, on versionKey CFBundleShortVersionString
2024-12-17 17:22:46 : INFO  : clickshare : appversion: 4.42.0-b18
2024-12-17 17:22:46 : INFO  : clickshare : Latest version of ClickShare is 4.42.0-b18
2024-12-17 17:22:46 : INFO  : clickshare : There is no newer version available.
2024-12-17 17:22:46 : INFO  : clickshare : Installomator did not close any apps, so no need to reopen any apps.
2024-12-17 17:22:46 : REQ   : clickshare : No newer version.
2024-12-17 17:22:46 : REQ   : clickshare : ################## End Installomator, exit code 0
```

Output when only the download URL parsing works:
```
sudo zsh /usr/local/Installomator/Installomator.sh clickshare
2024-12-17 17:19:56 : REQ   : clickshare : ################## Start Installomator v. 10.6, date 2024-08-30
2024-12-17 17:19:56 : INFO  : clickshare : ################## Version: 10.6
2024-12-17 17:19:56 : INFO  : clickshare : ################## Date: 2024-08-30
2024-12-17 17:19:56 : INFO  : clickshare : ################## clickshare
execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
expr: syntax error
execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
expr: syntax error
execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
expr: syntax error
execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
expr: syntax error
2024-12-17 17:19:58 : INFO  : clickshare : BLOCKING_PROCESS_ACTION=tell_user
2024-12-17 17:19:58 : INFO  : clickshare : NOTIFY=success
2024-12-17 17:19:58 : INFO  : clickshare : LOGGING=INFO
2024-12-17 17:19:58 : INFO  : clickshare : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-12-17 17:19:58 : INFO  : clickshare : Label type: appInDmgInZip
2024-12-17 17:19:58 : INFO  : clickshare : archiveName: ClickShare.zip
2024-12-17 17:19:58 : INFO  : clickshare : no blocking processes defined, using ClickShare as default
2024-12-17 17:19:58 : INFO  : clickshare : App(s) found: /Applications/ClickShare.app
2024-12-17 17:19:58 : INFO  : clickshare : found app at /Applications/ClickShare.app, version 4.41.0-b18, on versionKey CFBundleShortVersionString
2024-12-17 17:19:58 : INFO  : clickshare : appversion: 4.41.0-b18
2024-12-17 17:19:58 : INFO  : clickshare : Latest version of ClickShare is ..-b
2024-12-17 17:19:58 : REQ   : clickshare : Downloading https://securefiles.barco.com/tde/Active/SoftwareFiles/ApplicationSoftware/R3306192_61_ApplicationSw.zip?t=wT3h9M4WzUZsrjM68Pee%2fjcUsn%2bUc77%2flu508FTJqoE%3d&e=1734452698533&sv=2024-11-04&spr=https&st=2024-12-17T16%3A19%3A58Z&se=2024-12-17T16%3A24%3A58Z&sr=f&sp=r&sig=MgBsVS9LaUgQuhQ5qAG%2BnyfFS%2BlauTFoho97uI2OSEk%3D to ClickShare.zip
2024-12-17 17:20:02 : REQ   : clickshare : no more blocking processes, continue with update
2024-12-17 17:20:02 : REQ   : clickshare : Installing ClickShare
2024-12-17 17:20:02 : INFO  : clickshare : Unzipping ClickShare.zip
2024-12-17 17:20:02 : INFO  : clickshare : found dmg: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.bCzR8c2Gwe/ClickShare_Setup.dmg
2024-12-17 17:20:02 : INFO  : clickshare : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.bCzR8c2Gwe/ClickShare_Setup.dmg
2024-12-17 17:20:06 : INFO  : clickshare : Mounted: /Volumes/ClickShare Client 2
2024-12-17 17:20:06 : INFO  : clickshare : Verifying: /Volumes/ClickShare Client 2/ClickShare.app
2024-12-17 17:20:07 : INFO  : clickshare : Team ID matching: P6CDJZR997 (expected: P6CDJZR997 )
2024-12-17 17:20:07 : INFO  : clickshare : Downloaded version of ClickShare is 4.42.0-b18 on versionKey CFBundleShortVersionString (replacing version 4.41.0-b18).
2024-12-17 17:20:07 : INFO  : clickshare : App has LSMinimumSystemVersion: 10.15
2024-12-17 17:20:07 : WARN  : clickshare : Removing existing /Applications/ClickShare.app
2024-12-17 17:20:07 : INFO  : clickshare : Copy /Volumes/ClickShare Client 2/ClickShare.app to /Applications
2024-12-17 17:20:07 : WARN  : clickshare : Changing owner to lukas
2024-12-17 17:20:07 : INFO  : clickshare : Finishing...
2024-12-17 17:20:10 : INFO  : clickshare : App(s) found: /Applications/ClickShare.app
2024-12-17 17:20:10 : INFO  : clickshare : found app at /Applications/ClickShare.app, version 4.42.0-b18, on versionKey CFBundleShortVersionString
2024-12-17 17:20:11 : REQ   : clickshare : Installed ClickShare, version 4.42.0-b18
2024-12-17 17:20:11 : INFO  : clickshare : notifying
ERROR: Notifications are not allowed for this application
2024-12-17 17:20:12 : INFO  : clickshare : Installomator did not close any apps, so no need to reopen any apps.
2024-12-17 17:20:12 : REQ   : clickshare : All done!
2024-12-17 17:20:12 : REQ   : clickshare : ################## End Installomator, exit code 0
```