Create basecamp3applesilicon.sh
This label is for Basecamp 3 for Apple Silicon systems. The current label "basecamp3" is the intel installer.

Output:
2024-03-25 09:46:17 : REQ   : basecamp3applesilicon : ################## Start Installomator v. 10.6beta, date 2024-03-25
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : ################## Version: 10.6beta
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : ################## Date: 2024-03-25
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : ################## basecamp3applesilicon
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : DEBUG mode 1 enabled.
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : setting variable from argument DEBUG=0
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : name=Basecamp 3
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : appName=Basecamp 3.app
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : type=dmg
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : archiveName=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : downloadURL=https://bc3-desktop.s3.amazonaws.com/mac_arm64/basecamp3_arm64.dmg
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : curlOptions=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : appNewVersion=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : appCustomVersion function: Not defined
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : versionKey=CFBundleShortVersionString
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : packageID=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : pkgName=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : choiceChangesXML=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : expectedTeamID=2WNYUYRS7G
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : blockingProcesses=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : installerTool=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : CLIInstaller=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : CLIArguments=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : updateTool=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : updateToolArguments=
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : updateToolRunAsCurrentUser=
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : BLOCKING_PROCESS_ACTION=tell_user
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : NOTIFY=success
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : LOGGING=DEBUG
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : Label type: dmg
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : archiveName: Basecamp 3.dmg
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : no blocking processes defined, using Basecamp 3 as default
2024-03-25 09:46:17 : DEBUG : basecamp3applesilicon : Changing directory to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.K5sA0FEiFx
2024-03-25 09:46:17 : INFO  : basecamp3applesilicon : name: Basecamp 3, appName: Basecamp 3.app
2024-03-25 09:46:17.903 mdfind[1623:435911] [UserQueryParser] Loading keywords and predicates for locale "en_US"
2024-03-25 09:46:17.903 mdfind[1623:435911] [UserQueryParser] Loading keywords and predicates for locale "en"
2024-03-25 09:46:18.007 mdfind[1623:435911] Couldn't determine the mapping between prefab keywords and predicates.
2024-03-25 09:46:18 : WARN  : basecamp3applesilicon : No previous app found
2024-03-25 09:46:18 : WARN  : basecamp3applesilicon : could not find Basecamp 3.app
2024-03-25 09:46:18 : INFO  : basecamp3applesilicon : appversion:
2024-03-25 09:46:18 : INFO  : basecamp3applesilicon : Latest version not specified.
2024-03-25 09:46:18 : REQ   : basecamp3applesilicon : Downloading https://bc3-desktop.s3.amazonaws.com/mac_arm64/basecamp3_arm64.dmg to Basecamp 3.dmg
2024-03-25 09:46:18 : DEBUG : basecamp3applesilicon : No Dialog connection, just download
2024-03-25 09:46:28 : DEBUG : basecamp3applesilicon : File list: -rw-r--r--@ 1 root  wheel    87M Mar 25 09:46 Basecamp 3.dmg
2024-03-25 09:46:28 : DEBUG : basecamp3applesilicon : File type: Basecamp 3.dmg: zlib compressed data
2024-03-25 09:46:28 : DEBUG : basecamp3applesilicon : curl output was:
*   Trying 3.5.19.110:443...
* Connected to bc3-desktop.s3.amazonaws.com (3.5.19.110) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [333 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4969 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.s3.amazonaws.com
*  start date: Oct 10 00:00:00 2023 GMT
*  expire date: Jul  3 23:59:59 2024 GMT
*  subjectAltName: host "bc3-desktop.s3.amazonaws.com" matched cert's "*.s3.amazonaws.com"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* using HTTP/1.1
> GET /mac_arm64/basecamp3_arm64.dmg HTTP/1.1
> Host: bc3-desktop.s3.amazonaws.com
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-amz-id-2: 5XBq0eknPu+KLpX31wAlc8UXmEnetiU4PeYD82dg7cfdghfiXm5y4/GwHVCoXH+RJ2GAkY21R1Vi+eEikguxRQ==
< x-amz-request-id: 6E4FFQNTAFMG4QVN
< Date: Mon, 25 Mar 2024 14:46:19 GMT
< Last-Modified: Fri, 22 Sep 2023 13:04:24 GMT
< ETag: "08ff7fc079f73017775ac746fa196b34"
< x-amz-server-side-encryption: AES256
< x-amz-version-id: 0kJiLS4xpTxpZsuGnbRfN3_qxccsMFaK
< Accept-Ranges: bytes
< Content-Type: application/x-apple-diskimage
< Server: AmazonS3
< Content-Length: 91727114
<
{ [15791 bytes data]
* Connection #0 to host bc3-desktop.s3.amazonaws.com left intact

2024-03-25 09:46:28 : REQ   : basecamp3applesilicon : no more blocking processes, continue with update
2024-03-25 09:46:28 : REQ   : basecamp3applesilicon : Installing Basecamp 3
2024-03-25 09:46:28 : INFO  : basecamp3applesilicon : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.K5sA0FEiFx/Basecamp 3.dmg
2024-03-25 09:46:34 : DEBUG : basecamp3applesilicon : Debugging enabled, dmgmount output was:
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $C34A8150
Checksumming GPT Header (Primary GPT Header : 1)…
GPT Header (Primary GPT Header : 1): verified   CRC32 $C9462BE1
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $FE424713
Checksumming  (Apple_Free : 3)…
(Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
disk image (Apple_HFS : 4): verified   CRC32 $E395E400
Checksumming  (Apple_Free : 5)…
(Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $FE424713
Checksumming GPT Header (Backup GPT Header : 7)…
GPT Header (Backup GPT Header : 7): verified   CRC32 $0DE1FF3B
verified   CRC32 $B161226F
/dev/disk4          	GUID_partition_scheme
/dev/disk4s1        	Apple_HFS                      	/Volumes/Basecamp 3

2024-03-25 09:46:34 : INFO  : basecamp3applesilicon : Mounted: /Volumes/Basecamp 3
2024-03-25 09:46:34 : INFO  : basecamp3applesilicon : Verifying: /Volumes/Basecamp 3/Basecamp 3.app
2024-03-25 09:46:34 : DEBUG : basecamp3applesilicon : App size: 214M	/Volumes/Basecamp 3/Basecamp 3.app
2024-03-25 09:46:35 : DEBUG : basecamp3applesilicon : Debugging enabled, App Verification output was:
/Volumes/Basecamp 3/Basecamp 3.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Basecamp, LLC (2WNYUYRS7G)

2024-03-25 09:46:35 : INFO  : basecamp3applesilicon : Team ID matching: 2WNYUYRS7G (expected: 2WNYUYRS7G )
2024-03-25 09:46:35 : INFO  : basecamp3applesilicon : Installing Basecamp 3 version 2.3.14 on versionKey CFBundleShortVersionString.
2024-03-25 09:46:35 : INFO  : basecamp3applesilicon : App has LSMinimumSystemVersion: 10.13
2024-03-25 09:46:35 : INFO  : basecamp3applesilicon : Copy /Volumes/Basecamp 3/Basecamp 3.app to /Applications
2024-03-25 09:46:36 : DEBUG : basecamp3applesilicon : Debugging enabled, App copy output was:
Copying /Volumes/Basecamp 3/Basecamp 3.app

2024-03-25 09:46:36 : WARN  : basecamp3applesilicon : Changing owner to danny
2024-03-25 09:46:36 : INFO  : basecamp3applesilicon : Finishing...
2024-03-25 09:46:39 : INFO  : basecamp3applesilicon : App(s) found: /Applications/Basecamp 3.app
2024-03-25 09:46:39 : INFO  : basecamp3applesilicon : found app at /Applications/Basecamp 3.app, version 2.3.14, on versionKey CFBundleShortVersionString
2024-03-25 09:46:39 : REQ   : basecamp3applesilicon : Installed Basecamp 3, version 2.3.14
2024-03-25 09:46:39 : INFO  : basecamp3applesilicon : notifying
ERROR: Notifications are not allowed for this application
2024-03-25 09:46:39 : DEBUG : basecamp3applesilicon : Unmounting /Volumes/Basecamp 3
2024-03-25 09:46:40 : DEBUG : basecamp3applesilicon : Debugging enabled, Unmounting output was:
"disk4" ejected.
2024-03-25 09:46:40 : DEBUG : basecamp3applesilicon : Deleting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.K5sA0FEiFx
2024-03-25 09:46:40 : DEBUG : basecamp3applesilicon : Debugging enabled, Deleting tmpDir output was:
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.K5sA0FEiFx/Basecamp 3.dmg
2024-03-25 09:46:40 : DEBUG : basecamp3applesilicon : /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.K5sA0FEiFx
2024-03-25 09:46:40 : INFO  : basecamp3applesilicon : Installomator did not close any apps, so no need to reopen any apps.
2024-03-25 09:46:40 : REQ   : basecamp3applesilicon : All done!
2024-03-25 09:46:40 : REQ   : basecamp3applesilicon : ################## End Installomator, exit code 0