New label doctolib
Doctolib Pro is management software designed especially for healthcare professionals. This complete solution allows you to efficiently manage your appointments, monitor your patients, improve your visibility and optimize your administrative tasks

sudo ./assemble.sh -l /Users/savvas/CloudStation-NK/Geschäftsunterlagen/Anleitungen/Mosyle/Resources/InstallomatorLabels doctolib DEBUG=0
Password:
2025-04-18 16:29:25 : INFO  : doctolib : setting variable from argument DEBUG=0
2025-04-18 16:29:25 : INFO  : doctolib : Total items in argumentsArray: 1
2025-04-18 16:29:25 : INFO  : doctolib : argumentsArray: DEBUG=0
2025-04-18 16:29:25 : REQ   : doctolib : ################## Start Installomator v. 10.8, date 2025-04-18
2025-04-18 16:29:25 : INFO  : doctolib : ################## Version: 10.8
2025-04-18 16:29:25 : INFO  : doctolib : ################## Date: 2025-04-18
2025-04-18 16:29:25 : INFO  : doctolib : ################## doctolib
2025-04-18 16:29:26 : INFO  : doctolib : Reading arguments again: DEBUG=0
2025-04-18 16:29:26 : INFO  : doctolib : BLOCKING_PROCESS_ACTION=tell_user
2025-04-18 16:29:26 : INFO  : doctolib : NOTIFY=success
2025-04-18 16:29:26 : INFO  : doctolib : LOGGING=INFO
2025-04-18 16:29:26 : INFO  : doctolib : LOGO=/System/Applications/App Store.app/Contents/Resources/AppIcon.icns
2025-04-18 16:29:26 : INFO  : doctolib : Label type: dmg
2025-04-18 16:29:26 : INFO  : doctolib : archiveName: Doctolib.dmg
2025-04-18 16:29:26 : INFO  : doctolib : no blocking processes defined, using Doctolib as default
2025-04-18 16:29:26 : INFO  : doctolib : name: Doctolib, appName: Doctolib.app
2025-04-18 16:29:26 : INFO  : doctolib : App(s) found: /Users/savvas/CloudStation-NK/Geschäftsunterlagen/Anleitungen/Mosyle/MSP/PKGs/Doctolib.app
2025-04-18 16:29:26 : WARN  : doctolib : could not determine location of Doctolib.app
2025-04-18 16:29:26 : INFO  : doctolib : appversion:
2025-04-18 16:29:26 : INFO  : doctolib : Latest version of Doctolib is 2.60.0
2025-04-18 16:29:26 : REQ   : doctolib : Downloading https://doctolib-pro-desktop-production.s3.amazonaws.com/DoctolibProDesktop-latest.dmg to Doctolib.dmg
2025-04-18 16:29:31 : INFO  : doctolib : Downloaded Doctolib.dmg – Type is  bzip2 compressed data, block size = 100k – SHA is ee285ea0aa0a79a96bf1c166a2c884a0ef99309e – Size is 131420 kB
2025-04-18 16:29:31 : REQ   : doctolib : no more blocking processes, continue with update
2025-04-18 16:29:31 : REQ   : doctolib : Installing Doctolib
2025-04-18 16:29:31 : INFO  : doctolib : Mounting /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/tmp.dqI8AD9XP5/Doctolib.dmg
2025-04-18 16:29:42 : INFO  : doctolib : Mounted: /Volumes/Doctolib 2.60.0
2025-04-18 16:29:42 : INFO  : doctolib : Verifying: /Volumes/Doctolib 2.60.0/Doctolib.app
2025-04-18 16:29:52 : INFO  : doctolib : Team ID matching: 84K7XVJ72Q (expected: 84K7XVJ72Q )
2025-04-18 16:29:52 : INFO  : doctolib : Installing Doctolib version 2.60.0 on versionKey CFBundleShortVersionString.
2025-04-18 16:29:52 : INFO  : doctolib : App has LSMinimumSystemVersion: 11.0
2025-04-18 16:29:52 : INFO  : doctolib : Copy /Volumes/Doctolib 2.60.0/Doctolib.app to /Applications
2025-04-18 16:29:57 : WARN  : doctolib : Changing owner to savvas
2025-04-18 16:29:58 : INFO  : doctolib : Finishing...
2025-04-18 16:30:01 : INFO  : doctolib : App(s) found: /Applications/Doctolib.app
2025-04-18 16:30:01 : INFO  : doctolib : found app at /Applications/Doctolib.app, version 2.60.0, on versionKey CFBundleShortVersionString
2025-04-18 16:30:01 : REQ   : doctolib : Installed Doctolib, version 2.60.0
2025-04-18 16:30:01 : INFO  : doctolib : notifying
ERROR: Cannot find swiftDialog binary at /Library/Application Support/Dialog/Dialog.app/Contents/MacOS/Dialog
2025-04-18 16:30:01 : INFO  : doctolib : Installomator did not close any apps, so no need to reopen any apps.
2025-04-18 16:30:01 : REQ   : doctolib : All done!
2025-04-18 16:30:01 : REQ   : doctolib : ################## End Installomator, exit code 0